// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4226.Competition2020;

import org.usfirst.frc4226.Competition2020.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc4226.Competition2020.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick controller1;
    public JoystickButton armUpButton;
    public JoystickButton armDownButton;
    public JoystickButton winchUpButton;
    public JoystickButton winchDownButton;
    public JoystickButton spinnerLeftButton;
    public JoystickButton spinnerRightButton;
    public Joystick controller2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        controller2 = new Joystick(1);
        
        spinnerRightButton = new JoystickButton(controller2, 2);
        spinnerRightButton.whileHeld(new SpinnerRightCommand());
        spinnerLeftButton = new JoystickButton(controller2, 3);
        spinnerLeftButton.whileHeld(new SpinnerLeftCommand());
        winchDownButton = new JoystickButton(controller2, 1);
        winchDownButton.whileHeld(new WinchDownCommand());
        winchUpButton = new JoystickButton(controller2, 4);
        winchUpButton.whileHeld(new WinchUpCommand());
        armDownButton = new JoystickButton(controller2, 6);
        armDownButton.whileHeld(new ArmDownCommand());
        armUpButton = new JoystickButton(controller2, 5);
        armUpButton.whileHeld(new ArmUpCommand());
        controller1 = new Joystick(0);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("DriveCommand", new DriveCommand());
        SmartDashboard.putData("IntakeCommand", new IntakeCommand());
        SmartDashboard.putData("ArmUpCommand", new ArmUpCommand());
        SmartDashboard.putData("ArmDownCommand", new ArmDownCommand());
        SmartDashboard.putData("FlywheelCommand", new FlywheelCommand());
        SmartDashboard.putData("SpinnerLeftCommand", new SpinnerLeftCommand());
        SmartDashboard.putData("SpinnerRightCommand", new SpinnerRightCommand());
        SmartDashboard.putData("WinchUpCommand", new WinchUpCommand());
        SmartDashboard.putData("WinchDownCommand", new WinchDownCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getController1() {
        return controller1;
    }

    public Joystick getController2() {
        return controller2;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

